@startuml
!theme plain
skinparam backgroundColor #FAFAFA
skinparam defaultFontName Arial
skinparam defaultFontSize 13

title Hotel Booking Management System — Use Case Diagram

left to right direction
skinparam actorStyle awesome

actor "Admin" as Admin
actor "Guest" as Guest

rectangle "Rangoon Heritage Hotel" {
  usecase "Login" as UC_Login
  usecase "Register" as UC_Register
  usecase "Manage Profile" as UC_Profile
  usecase "Manage Password" as UC_ManagePassword
  usecase "Upload Avatar" as UC_Avatar

  usecase "Cancel/Confrim Room Booking" as UC_RoomBooking
  usecase "Cancel/Confrim Buffet Booking" as UC_BookBuffet
  usecase "Write Review" as UC_WriteReview

  usecase "Manage Room" as UC_ManageRoom
  usecase "Manage Booking" as UC_ManageBooking
  usecase "Manage Customer" as UC_ManageCustomer
  usecase "Manage Promotion" as UC_ManagePromotion
  usecase "Manage Membership Tier" as UC_ManageTier
  usecase "Delete Review" as UC_ManageReview
  usecase "Manage Buffet" as UC_ManageBuffet
  usecase "Manage Buffet Booking" as UC_ManageBuffetBooking
}

Admin --> UC_ManageRoom
Admin --> UC_ManageBooking
Admin --> UC_ManageCustomer
Admin --> UC_ManagePromotion
Admin --> UC_ManageTier
Admin --> UC_ManageReview
Admin --> UC_ManageBuffet
Admin --> UC_ManageBuffetBooking

Admin --> UC_Login
Admin --> UC_Register
Admin --> UC_Profile
Admin --> UC_ManagePassword
Admin --> UC_Avatar

UC_Login <-- Guest
UC_Register <-- Guest
UC_Profile <-- Guest
UC_ManagePassword <-- Guest
UC_Avatar <-- Guest

UC_RoomBooking <-- Guest
UC_BookBuffet <-- Guest
UC_WriteReview <-- Guest

@enduml