export const rooms = [
  {
    id: "1",
    roomNumber: "101",
    type: "Single",
    pricePerNight: 100.0,
    capacity: 1,
    isAvailable: true,
    location: "Yangon",
    title: "Cozy Single Room",
    description: `This cozy single room is designed for solo travelers seeking comfort and relaxation. The room features a plush queen-sized bed with premium linens, a spacious work desk, and a comfortable armchair. Large windows allow natural light to flood the room, offering a bright and airy atmosphere. Modern amenities include high-speed Wi-Fi, a flat-screen TV, and a mini-fridge. The en-suite bathroom is equipped with a rain shower, complimentary toiletries, and soft towels. Perfect for business travelers or those exploring the city, this room provides a peaceful retreat after a busy day.`,
    images: [
      { url: "https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg", public_id: "room1-1" },
      { url: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg", public_id: "room1-2" },
      { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room1-3" },
      { url: "https://images.pexels.com/photos/6782346/pexels-photo-6782346.jpeg", public_id: "room1-4" },
      { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room1-5" },
    ],
  },
  {
    id: "2",
    roomNumber: "102",
    type: "Double",
    pricePerNight: 150.0,
    capacity: 2,
    isAvailable: true,
    location: "Yangon",
    title: "Spacious Double Room",
    description: `Ideal for couples or small families, this spacious double room offers a comfortable king-sized bed and a cozy sitting area. The room is decorated in warm, neutral tones, creating a welcoming and relaxing environment. Large windows provide stunning views of the city skyline, and blackout curtains ensure a restful night's sleep. Amenities include a flat-screen TV, a coffee maker, and a well-stocked minibar. The en-suite bathroom features a bathtub, a separate rain shower, and luxurious toiletries. Whether you're here for business or leisure, this room provides the perfect blend of comfort and convenience.`,
    images: [
      { url: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg", public_id: "room2-1" },
      { url: "https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg", public_id: "room2-2" },
      { url: "https://images.pexels.com/photos/7512038/pexels-photo-7512038.jpeg", public_id: "room2-3" },
      { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room2-4" },
      { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room2-5" },
    ],
  },
  {
    id: "3",
    roomNumber: "103",
    type: "Suite",
    pricePerNight: 250.0,
    capacity: 4,
    isAvailable: false,
    location: "Yangon",
    title: "Luxury Suite",
    description: `Experience the ultimate in luxury with this spacious suite, perfect for families or groups. The suite features a separate living area with a plush sofa, a dining table, and a fully equipped kitchenette. The bedroom boasts a king-sized bed with premium bedding, and the en-suite bathroom includes a Jacuzzi tub and a separate rain shower. Floor-to-ceiling windows offer breathtaking views of the surrounding landscape. Additional amenities include a 55-inch flat-screen TV, a Nespresso machine, and a private balcony. This suite is designed to provide a truly indulgent stay, combining elegance with modern comforts.`,
    images: [
      { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room3-1" },
      { url: "https://images.pexels.com/photos/7512038/pexels-photo-7512038.jpeg", public_id: "room3-2" },
      { url: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg", public_id: "room3-3" },
      { url: "https://images.pexels.com/photos/6782346/pexels-photo-6782346.jpeg", public_id: "room3-4" },
      { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room3-5" },
    ],
  },
  {
    id: "4",
    roomNumber: "104",
    type: "Single",
    pricePerNight: 120.0,
    capacity: 1,
    isAvailable: true,
    location: "Yangon",
    title: "Elegant Single Room",
    description: `This elegant single room is designed for the discerning traveler who appreciates style and comfort. The room features a comfortable queen-sized bed with high-quality linens, a sleek work desk, and a cozy reading nook. The modern decor is complemented by soft lighting and tasteful artwork. Amenities include a smart TV, a coffee maker, and a well-stocked minibar. The en-suite bathroom is equipped with a rain shower, premium toiletries, and fluffy towels. Whether you're here for work or leisure, this room offers a serene and sophisticated retreat.`,
    images: [
      { url: "https://images.pexels.com/photos/6782346/pexels-photo-6782346.jpeg", public_id: "room4-1" },
      { url: "https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg", public_id: "room4-2" },
      { url: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg", public_id: "room4-3" },
      { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room4-4" },
      { url: "https://images.pexels.com/photos/7512038/pexels-photo-7512038.jpeg", public_id: "room4-5" },
    ],
  },
  {
    id: "5",
    roomNumber: "105",
    type: "Double",
    pricePerNight: 180.0,
    capacity: 2,
    isAvailable: true,
    location: "Yangon",
    title: "Deluxe Double Room",
    description: `This deluxe double room offers a perfect blend of comfort and style, ideal for couples or friends traveling together. The room features a king-sized bed with luxurious bedding, a cozy seating area, and a private balcony with stunning city views. The modern decor is complemented by soft lighting and elegant furnishings. Amenities include a flat-screen TV, a coffee maker, and a minibar. The en-suite bathroom features a rain shower, premium toiletries, and plush towels. Whether you're here for business or leisure, this room provides a relaxing and enjoyable stay.`,
    images: [
      { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room5-1" },
      { url: "https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg", public_id: "room5-2" },
      { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room5-3" },
      { url: "https://images.pexels.com/photos/6782346/pexels-photo-6782346.jpeg", public_id: "room5-4" },
      { url: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg", public_id: "room5-5" },
    ],
  },
  {
    id: "6",
    roomNumber: "106",
    type: "Suite",
    pricePerNight: 300.0,
    capacity: 4,
    isAvailable: false,
    location: "Yangon",
    title: "Premium Suite",
    description: `Indulge in the ultimate luxury with this premium suite, designed for those who seek the finest accommodations. The suite features a spacious living area with a plush sofa, a dining table, and a fully equipped kitchenette. The bedroom offers a king-sized bed with premium bedding, and the en-suite bathroom includes a Jacuzzi tub and a separate rain shower. Floor-to-ceiling windows provide breathtaking views of the city skyline. Additional amenities include a 55-inch flat-screen TV, a Nespresso machine, and a private balcony. This suite is perfect for families or groups looking for a luxurious and memorable stay.`,
    images: [
      { url: "https://images.pexels.com/photos/7512038/pexels-photo-7512038.jpeg", public_id: "room6-1" },
      { url: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg", public_id: "room6-2" },
      { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room6-3" },
      { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room6-4" },
      { url: "https://images.pexels.com/photos/6782346/pexels-photo-6782346.jpeg", public_id: "room6-5" },
    ],
  },
  {
    id: "7",
    roomNumber: "107",
    type: "Single",
    pricePerNight: 110.0,
    capacity: 1,
    isAvailable: true,
    location: "Yangon",
    title: "Comfortable Single Room",
    description: `This comfortable single room is perfect for solo travelers seeking a relaxing and hassle-free stay. The room features a cozy queen-sized bed with soft linens, a compact work desk, and a comfortable armchair. The minimalist decor creates a calming atmosphere, while large windows let in plenty of natural light. Amenities include a flat-screen TV, high-speed Wi-Fi, and a mini-fridge. The en-suite bathroom is equipped with a rain shower, complimentary toiletries, and fluffy towels. Whether you're here for work or leisure, this room offers a peaceful and comfortable retreat.`,
    images: [
      { url: "https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg", public_id: "room7-1" },
      { url: "https://images.pexels.com/photos/7512038/pexels-photo-7512038.jpeg", public_id: "room7-2" },
      { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room7-3" },
      { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room7-4" },
      { url: "https://images.pexels.com/photos/6782346/pexels-photo-6782346.jpeg", public_id: "room7-5" },
    ],
  },
  {
    id: "8",
    roomNumber: "108",
    type: "Double",
    pricePerNight: 160.0,
    capacity: 2,
    isAvailable: true,
    location: "Yangon",
    title: "Romantic Double Room",
    description: `This romantic double room is perfect for couples looking for a cozy and intimate getaway. The room features a king-sized bed with luxurious bedding, a comfortable seating area, and soft lighting to create a warm and inviting atmosphere. Large windows offer stunning views of the surrounding landscape, and blackout curtains ensure a restful night's sleep. Amenities include a flat-screen TV, a coffee maker, and a minibar. The en-suite bathroom features a bathtub, a separate rain shower, and premium toiletries. Whether you're celebrating a special occasion or simply enjoying a quiet retreat, this room provides the perfect setting.`,
    images: [
      { url: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg", public_id: "room8-1" },
      { url: "https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg", public_id: "room8-2" },
      { url: "https://images.pexels.com/photos/7512038/pexels-photo-7512038.jpeg", public_id: "room8-3" },
      { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room8-4" },
      { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room8-5" },
    ],
  },
  {
    id: "9",
    roomNumber: "109",
    type: "Suite",
    pricePerNight: 280.0,
    capacity: 4,
    isAvailable: false,
    location: "Yangon",
    title: "Executive Suite",
    description: `This executive suite is designed for travelers who demand the best in comfort and convenience. The suite features a separate living area with a plush sofa, a dining table, and a fully equipped kitchenette. The bedroom offers a king-sized bed with premium bedding, and the en-suite bathroom includes a Jacuzzi tub and a separate rain shower. Floor-to-ceiling windows provide stunning views of the city skyline. Additional amenities include a 55-inch flat-screen TV, a Nespresso machine, and a private balcony. Whether you're here for business or leisure, this suite offers a luxurious and memorable stay.`,
    images: [
      { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room9-1" },
      { url: "https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg", public_id: "room9-2" },
      { url: "https://images.pexels.com/photos/7512038/pexels-photo-7512038.jpeg", public_id: "room9-3" },
      { url: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg", public_id: "room9-4" },
      { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room9-5" },
    ],
  },
  {
    id: "10",
    roomNumber: "110",
    type: "Single",
    pricePerNight: 130.0,
    capacity: 1,
    isAvailable: true,
    location: "Yangon",
    title: "Modern Single Room",
    description: `This modern single room is perfect for solo travelers who appreciate contemporary design and comfort. The room features a comfortable queen-sized bed with high-quality linens, a sleek work desk, and a cozy reading nook. The minimalist decor is complemented by soft lighting and tasteful artwork. Amenities include a smart TV, a coffee maker, and a well-stocked minibar. The en-suite bathroom is equipped with a rain shower, premium toiletries, and fluffy towels. Whether you're here for work or leisure, this room offers a serene and sophisticated retreat.`,
    images: [
      { url: "https://images.pexels.com/photos/7512038/pexels-photo-7512038.jpeg", public_id: "room10-1" },
      { url: "https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg", public_id: "room10-2" },
      { url: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg", public_id: "room10-3" },
      { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room10-4" },
      { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room10-5" },
    ],
  },
  {
    id: "11",
    roomNumber: "201",
    type: "Family",
    pricePerNight: 220.0,
    capacity: 5,
    isAvailable: true,
    location: "Yangon",
    title: "Heritage Family Room",
    description: `This heritage family room is arranged for families who need extra space without sacrificing comfort. The room includes two queen-sized beds, a lounge corner, a writing desk, and generous wardrobe storage. Warm wood finishes and soft lighting create a calm setting after a day of sightseeing. Amenities include high-speed Wi-Fi, a smart TV, a mini-fridge, a tea station, and blackout curtains. The en-suite bathroom has a rain shower, a large vanity, soft towels, and family-friendly toiletries. It is a practical and polished choice for longer stays in Yangon.`,
    images: [
      { url: "https://images.pexels.com/photos/262048/pexels-photo-262048.jpeg", public_id: "room11-1" },
      { url: "https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg", public_id: "room11-2" },
      { url: "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg", public_id: "room11-3" },
      { url: "https://images.pexels.com/photos/271619/pexels-photo-271619.jpeg", public_id: "room11-4" },
      { url: "https://images.pexels.com/photos/237371/pexels-photo-237371.jpeg", public_id: "room11-5" },
    ],
  },
  {
    id: "12",
    roomNumber: "202",
    type: "Twin",
    pricePerNight: 145.0,
    capacity: 2,
    isAvailable: true,
    location: "Yangon",
    title: "City View Twin Room",
    description: `This city view twin room is ideal for friends, colleagues, or guests who prefer separate beds. The room features two plush single beds, a compact work desk, a small seating area, and large windows overlooking Mandalay. Neutral decor, crisp linens, and practical lighting make the space easy to use throughout the day. Amenities include Wi-Fi, a flat-screen TV, a coffee maker, a safe, and a mini-fridge. The bathroom includes a walk-in shower, fresh towels, and complimentary toiletries for a clean and convenient stay.`,
    images: [
      { url: "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg", public_id: "room12-1" },
      { url: "https://images.pexels.com/photos/271643/pexels-photo-271643.jpeg", public_id: "room12-2" },
      { url: "https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg", public_id: "room12-3" },
      { url: "https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg", public_id: "room12-4" },
      { url: "https://images.pexels.com/photos/271619/pexels-photo-271619.jpeg", public_id: "room12-5" },
    ],
  },
  {
    id: "13",
    roomNumber: "203",
    type: "Suite",
    pricePerNight: 340.0,
    capacity: 4,
    isAvailable: true,
    location: "Yangon",
    title: "Lakefront Signature Suite",
    description: `This lakefront signature suite offers a quiet retreat with a separate bedroom, a living room, and a private balcony facing the water. The bedroom includes a king-sized bed with premium linens, while the living area provides a sofa, dining table, and coffee station. Large windows bring in natural light and frame the surrounding landscape. Amenities include high-speed Wi-Fi, a large smart TV, a mini-bar, and climate control. The bathroom features a soaking tub, a rain shower, premium toiletries, and soft robes for a relaxed stay.`,
    images: [
      { url: "https://images.pexels.com/photos/210604/pexels-photo-210604.jpeg", public_id: "room13-1" },
      { url: "https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg", public_id: "room13-2" },
      { url: "https://images.pexels.com/photos/1743231/pexels-photo-1743231.jpeg", public_id: "room13-3" },
      { url: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg", public_id: "room13-4" },
      { url: "https://images.pexels.com/photos/276671/pexels-photo-276671.jpeg", public_id: "room13-5" },
    ],
  },
  {
    id: "14",
    roomNumber: "204",
    type: "Double",
    pricePerNight: 175.0,
    capacity: 2,
    isAvailable: true,
    location: "Yangon",
    title: "Business Deluxe Room",
    description: `This business deluxe room is built for guests who need a quiet and efficient base. The room includes a king-sized bed, a wide desk, an ergonomic chair, and a comfortable reading area. Its clean layout keeps luggage, work materials, and personal items organized during short or extended stays. Amenities include reliable Wi-Fi, a smart TV, a coffee maker, a laptop safe, and a mini-fridge. The bathroom offers a rain shower, bright vanity lighting, premium toiletries, and fresh towels for a polished business travel experience.`,
    images: [
      { url: "https://images.pexels.com/photos/271619/pexels-photo-271619.jpeg", public_id: "room14-1" },
      { url: "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg", public_id: "room14-2" },
      { url: "https://images.pexels.com/photos/262048/pexels-photo-262048.jpeg", public_id: "room14-3" },
      { url: "https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg", public_id: "room14-4" },
      { url: "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg", public_id: "room14-5" },
    ],
  },
  {
    id: "15",
    roomNumber: "205",
    type: "Single",
    pricePerNight: 115.0,
    capacity: 1,
    isAvailable: true,
    location: "Yangon",
    title: "Hill View Single Room",
    description: `This hill view single room gives solo travelers a compact and comfortable place to rest. The room includes a queen-sized bed, a writing desk, a reading lamp, and a soft lounge chair beside the window. Light colors and simple furnishings keep the space calm and uncluttered. Amenities include Wi-Fi, a flat-screen TV, a mini-fridge, a safe, and a tea station. The en-suite bathroom includes a walk-in shower, fresh towels, and essential toiletries, making it suitable for both short visits and quiet work trips.`,
    images: [
      { url: "https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg", public_id: "room15-1" },
      { url: "https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg", public_id: "room15-2" },
      { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room15-3" },
      { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room15-4" },
      { url: "https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg", public_id: "room15-5" },
    ],
  },
  {
    id: "16",
    roomNumber: "206",
    type: "Villa",
    pricePerNight: 420.0,
    capacity: 6,
    isAvailable: false,
    location: "Yangon",
    title: "Beachfront Private Villa",
    description: `This beachfront private villa is designed for groups and families who want privacy near the shoreline. The villa includes two bedrooms, a living area, a dining corner, and a private outdoor seating space. Large glass doors connect the interior to the beach-facing terrace and fill the rooms with natural light. Amenities include Wi-Fi, smart TVs, a coffee station, a mini-bar, and climate control. The bathrooms feature rain showers, premium toiletries, soft robes, and double vanities. It is a spacious option for a coastal getaway.`,
    images: [
      { url: "https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg", public_id: "room16-1" },
      { url: "https://images.pexels.com/photos/261395/pexels-photo-261395.jpeg", public_id: "room16-2" },
      { url: "https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg", public_id: "room16-3" },
      { url: "https://images.pexels.com/photos/261327/pexels-photo-261327.jpeg", public_id: "room16-4" },
      { url: "https://images.pexels.com/photos/261181/pexels-photo-261181.jpeg", public_id: "room16-5" },
    ],
  },
  {
    id: "17",
    roomNumber: "207",
    type: "Double",
    pricePerNight: 165.0,
    capacity: 2,
    isAvailable: true,
    location: "Yangon",
    title: "Temple View Double Room",
    description: `This temple view double room gives couples a warm and peaceful base in Bagan. The room features a king-sized bed, woven accent furniture, a compact work desk, and windows that catch the soft evening light. The layout balances comfort with local character, making it easy to unwind after exploring nearby landmarks. Amenities include Wi-Fi, a flat-screen TV, a coffee maker, a mini-fridge, and blackout curtains. The en-suite bathroom includes a rain shower, soft towels, and complimentary toiletries for a relaxed stay.`,
    images: [
      { url: "https://images.pexels.com/photos/271643/pexels-photo-271643.jpeg", public_id: "room17-1" },
      { url: "https://images.pexels.com/photos/271619/pexels-photo-271619.jpeg", public_id: "room17-2" },
      { url: "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg", public_id: "room17-3" },
      { url: "https://images.pexels.com/photos/237371/pexels-photo-237371.jpeg", public_id: "room17-4" },
      { url: "https://images.pexels.com/photos/1743231/pexels-photo-1743231.jpeg", public_id: "room17-5" },
    ],
  },
  {
    id: "18",
    roomNumber: "208",
    type: "Suite",
    pricePerNight: 310.0,
    capacity: 4,
    isAvailable: true,
    location: "Yangon",
    title: "Mountain Terrace Suite",
    description: `This mountain terrace suite combines generous indoor space with a private terrace for cooler evenings. The suite includes a king-sized bedroom, a separate living area, a small dining table, and a coffee station. Natural textures, soft fabrics, and wide windows create a relaxing mountain retreat. Amenities include high-speed Wi-Fi, a smart TV, a mini-bar, a safe, and climate control. The bathroom includes a soaking tub, a separate rain shower, premium toiletries, and soft robes. It is well suited for couples or small families.`,
    images: [
      { url: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg", public_id: "room18-1" },
      { url: "https://images.pexels.com/photos/1743231/pexels-photo-1743231.jpeg", public_id: "room18-2" },
      { url: "https://images.pexels.com/photos/210604/pexels-photo-210604.jpeg", public_id: "room18-3" },
      { url: "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg", public_id: "room18-4" },
      { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room18-5" },
    ],
  },
  {
    id: "19",
    roomNumber: "209",
    type: "Twin",
    pricePerNight: 155.0,
    capacity: 2,
    isAvailable: true,
    location: "Yangon",
    title: "Garden Courtyard Twin Room",
    description: `This garden courtyard twin room is a practical choice for two guests who want easy access to hotel facilities. The room includes two single beds, a shared bedside table, a desk, and a sitting chair near the window. Courtyard-facing windows help keep the space bright while maintaining a calmer atmosphere. Amenities include Wi-Fi, a flat-screen TV, a mini-fridge, a coffee maker, and a safe. The bathroom has a rain shower, fresh towels, and complimentary toiletries, keeping the room comfortable for both leisure and business stays.`,
    images: [
      { url: "https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg", public_id: "room19-1" },
      { url: "https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg", public_id: "room19-2" },
      { url: "https://images.pexels.com/photos/271643/pexels-photo-271643.jpeg", public_id: "room19-3" },
      { url: "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg", public_id: "room19-4" },
      { url: "https://images.pexels.com/photos/262048/pexels-photo-262048.jpeg", public_id: "room19-5" },
    ],
  },
  {
    id: "20",
    roomNumber: "210",
    type: "Presidential",
    pricePerNight: 650.0,
    capacity: 6,
    isAvailable: true,
    location: "Yangon",
    title: "Presidential Heritage Suite",
    description: `This presidential heritage suite is the most spacious accommodation in the collection. The suite includes a master bedroom, a guest bedroom, a formal living room, a dining area, and a private balcony with city views. Premium furnishings, warm lighting, and carefully arranged work and lounge spaces make it suitable for VIP guests, families, and executive stays. Amenities include high-speed Wi-Fi, large smart TVs, a mini-bar, a coffee station, and private check-in support. The bathrooms include soaking tubs, rain showers, double vanities, robes, and premium toiletries.`,
    images: [
      { url: "https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg", public_id: "room20-1" },
      { url: "https://images.pexels.com/photos/276671/pexels-photo-276671.jpeg", public_id: "room20-2" },
      { url: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg", public_id: "room20-3" },
      { url: "https://images.pexels.com/photos/210604/pexels-photo-210604.jpeg", public_id: "room20-4" },
      { url: "https://images.pexels.com/photos/1743231/pexels-photo-1743231.jpeg", public_id: "room20-5" },
    ],
  },
];
